import { Buffer } from "buffer";

////////////////////////////////////////////////////////////////////////////////

export interface CloudProtocol {
    name: string;
    category: string;
    downloadUrl: string;
}

/**
 * The protocol cloud contract is not available during P0. These entries keep
 * the protocol center demonstrable and deterministic without requiring a
 * network service. The mock URL is intentionally explicit so it cannot be
 * mistaken for a production endpoint.
 */
export const MOCK_PROTOCOLS: CloudProtocol[] = [
    {
        name: "UART Basic",
        category: "Communication",
        downloadUrl: "mock://download/uart-basic.json"
    },
    {
        name: "I2C Sensor",
        category: "Communication",
        downloadUrl: "mock://download/i2c-sensor.json"
    },
    {
        name: "Modbus RTU",
        category: "Industrial",
        downloadUrl: "mock://download/modbus-rtu.json"
    },
    {
        name: "SCPI Power Supply",
        category: "Instrument",
        downloadUrl: "mock://download/scpi-power-supply.json"
    },
    {
        name: "CANopen Device",
        category: "Industrial",
        downloadUrl: "mock://download/canopen-device.json"
    },
    {
        name: "BLE UART",
        category: "Wireless",
        downloadUrl: "mock://download/ble-uart.json"
    }
];

function getMockMode(endpoint: string) {
    const normalizedEndpoint = endpoint.trim().toLowerCase();
    if (normalizedEndpoint.includes("download-error")) {
        return "download-error";
    }
    if (normalizedEndpoint.includes("empty")) {
        return "empty";
    }
    if (normalizedEndpoint.includes("error")) {
        return "error";
    }
    return "normal";
}

export function isMockProtocolEndpoint(endpoint: string) {
    return endpoint.trim().toLowerCase().startsWith("mock://");
}

export function searchMockProtocols(endpoint: string, query: string) {
    const mode = getMockMode(endpoint);
    if (mode === "error") {
        throw new Error("Mock cloud search failed (use mock://protocols to retry).");
    }
    if (mode === "empty") {
        return [];
    }

    const normalizedQuery = query.trim().toLowerCase();
    const results = MOCK_PROTOCOLS.filter(
        protocol =>
            !normalizedQuery ||
            `${protocol.name} ${protocol.category}`
                .toLowerCase()
                .includes(normalizedQuery)
    );
    if (mode === "download-error") {
        return results.map(protocol => ({
            ...protocol,
            downloadUrl: protocol.downloadUrl.replace(
                "mock://download/",
                "mock://download-error/"
            )
        }));
    }
    return results;
}

export async function downloadMockProtocol(entry: CloudProtocol) {
    if (
        getMockMode(entry.downloadUrl) === "download-error" ||
        entry.downloadUrl.toLowerCase().includes("download-error")
    ) {
        throw new Error("Mock protocol download failed.");
    }

    const contents = {
        schema: "eez-studio.protocol",
        version: 1,
        name: entry.name,
        category: entry.category,
        description: "P0 demo protocol generated by the local mock catalog."
    };
    return Buffer.from(JSON.stringify(contents, null, 2) + "\n", "utf8");
}
